# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Essence of Code"
email: marvelez@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
   I started this blog because I want to start sharing my ideas and projects with the world.  
   I am interested in programming languages, software engineering, and computer science education.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://martinvelez.github.io" # the base hostname & protocol for your site
twitter_username: martin_velez_ 
github_username: martinvelez 
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
